### ISSUE TITLE
Could not start region modalities

### ISSUE THREAD

**Issue by nilsmelchert** [Jianxff/pysrt3d#2]
Hi,

when I am trying to adopt the `demo.py` file to my own geometry `.obj` file, I am getting the following error:

```bash
Traceback (most recent call last):
  File "/root/pysrt3d/example/demo.py", line 68, in <module>
    tracker.update(image=image_rgb)
RuntimeError: Could not start region modalities
```

What could be the cause for this error? Could it be a scaling problem of the geometry, that I am using? I am pretty sure that the camera matrix ist correct. However, it is hard to debug for me weather the initial pose from the `pose.txt` file ist correct.

Would really appreciate your opinion.

**Comment by Jianxff** [comment]
Hi，
Here are some tips:
- the argument `unit_in_meter` should fit your model
- the initial pose matrix must under opencv coordinate, in which way the z value must be positive to make the model visible.

You can follow this #1 .

If you apply it on real-time webcam stream, you can manually align it just as the video on README. If not, you can set an approximate one then modifying.

**Comment by nilsmelchert** [comment]
First of all, thank you for your reply and of course for the implementation, which makes the original code much more useful for research purposes. 

The problem was that my original pose matrix was defined in mm. After converting it to m, it worked fine. 

Thanks again and I will now close this issue.
